cache_dir: .cache
output_dir: rss
comics:
  fingerpori:
    url: http://www.hs.fi/fingerpori/
    image_selector: "div#full-comic > div > img"
    link_selector: "div#full-comic .comic-details div.fb-like"
    link_attr: "data-href"
  viivijawagner:
    url: http://www.hs.fi/viivijawagner/
    image_selector: "div#full-comic > div > img"
    link_selector: "div#full-comic .comic-details div.fb-like"
    link_attr: "data-href"
